### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test_user2@gmail.com",
  "password": "Whatever"
}

### Fail to create a new user 400
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test98@gmail",
  "password": 213
}

### Get user by ID
GET http://localhost:3000/auth/3

### Get users by email
GET http://localhost:3000/auth?email=test_user2@gmail.com