### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test_user6@gmail.com",
  "password": "Whatever"
}

### Fail to create a new user 400
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "test98@gmail",
  "password": 213
}
